// This file is generated by esbuild from server/vercel-entry.ts
// It's the Vercel serverless function entry point
// See package.json build script for how it's compiled

module.exports = require('./index.js');